namespace Adk.Analyzer;

static class NetworkManagerSource
{
    public const string Source = """
// <auto-generated/>
using System;
using System.Collections.Generic;
using ProtoBuf;
using Sandbox.ModAPI;
using VRage.Game;
using VRage.Game.ModAPI;
using VRage.Utils;

namespace Generated
{
    public sealed class NetworkParameters
    {
        public ushort Port { get; private set; }
        public int MaxWirePacketBytes { get; private set; }
        public int MaxFragmentedPacketBytes { get; private set; }
        public int MaxFragmentChunks { get; private set; }

        public NetworkParameters(
            ushort port,
            int maxWirePacketBytes,
            int maxFragmentedPacketBytes,
            int maxFragmentChunks)
        {
            if (maxWirePacketBytes <= 0)
                throw new ArgumentException(nameof(maxWirePacketBytes));
            if (maxFragmentedPacketBytes <= 0)
                throw new ArgumentException(nameof(maxFragmentedPacketBytes));
            if (maxFragmentChunks <= 0)
                throw new ArgumentException(nameof(maxFragmentChunks));

            Port = port;
            MaxWirePacketBytes = maxWirePacketBytes;
            MaxFragmentedPacketBytes = maxFragmentedPacketBytes;
            MaxFragmentChunks = maxFragmentChunks;
        }
    }

    public partial class NetworkManager : IDisposable, ISingleton<NetworkManager>
    {
        const int NETWORK_FRAGMENT_ID = 127;
        static readonly long FragmentAssemblyExpiryTicks = TimeSpan.TicksPerSecond * 15;

        public static NetworkManager Instance { get; private set; }
        public NetworkParameters Parameters { get; private set; }

        readonly ushort _channelId;
        int _nextFragmentTransferId;
        readonly Dictionary<string, FragmentAssembly> _fragmentAssemblies =
            new Dictionary<string, FragmentAssembly>();

        public NetworkManager(NetworkParameters parameters)
        {
            if (parameters == null)
                throw new ArgumentNullException(nameof(parameters));
            if (Instance != null)
                throw new InvalidOperationException("A NetworkManager instance is already registered");

            Parameters = parameters;
            _channelId = parameters.Port;
            Instance = this;
        }

        public void Init()
        {
            Register();
        }

        public void Register()
        {
            MyAPIGateway.Multiplayer.RegisterSecureMessageHandler(_channelId, ReceivedPacket);
        }

        public void Unregister()
        {
            MyAPIGateway.Multiplayer.UnregisterSecureMessageHandler(_channelId, ReceivedPacket);
        }

        public void Dispose()
        {
            Unregister();
            if (ReferenceEquals(Instance, this))
                Instance = null;
        }

        public void TransmitToServer(
            NetworkPackage data,
            bool sendToAllPlayers = true,
            bool sendToSender = false)
        {
            var packet = new PacketBase(data.Id, sendToAllPlayers, sendToSender);
            packet.Wrap(data);
            var raw = MyAPIGateway.Utilities.SerializeToBinary(packet);
            if (!SendToServer(raw))
            {
                MyLog.Default.WriteLineAndConsole(
                    $"[ADK.Network] Failed to send packet {data.Id} to server ({raw.Length} bytes)");
            }
        }

        public void TransmitToPlayer(NetworkPackage data, ulong playerId, bool sendToSender = false)
        {
            var packet = new PacketBase(data.Id, false, sendToSender);
            packet.Wrap(data);
            var raw = MyAPIGateway.Utilities.SerializeToBinary(packet);
            if (!SendToPlayer(raw, playerId))
            {
                MyLog.Default.WriteLineAndConsole(
                    $"[ADK.Network] Failed to send packet {data.Id} to player {playerId} ({raw.Length} bytes)");
            }
        }

        void ReceivedPacket(ushort handler, byte[] raw, ulong id, bool isFromServer)
        {
            try
            {
                var packet = MyAPIGateway.Utilities.SerializeFromBinary<PacketBase>(raw);
                if (packet.Id == NETWORK_FRAGMENT_ID)
                {
                    if (!TryAssembleFragment(packet, id, isFromServer, out raw))
                        return;

                    packet = MyAPIGateway.Utilities.SerializeFromBinary<PacketBase>(raw);
                }

                HandlePacket(packet, id, isFromServer);
            }
            catch (Exception e)
            {
                MyLog.Default.WriteLineAndConsole($"[ADK.Network] Malformed packet from {id}!");
                MyLog.Default.WriteLineAndConsole($"{e.Message}\n{e.StackTrace}");

                if (MyAPIGateway.Session?.Player != null)
                {
                    MyAPIGateway.Utilities.ShowNotification(
                        $"[ERROR: {GetType().FullName}: {e.Message} | Send SpaceEngineers.Log to mod author]",
                        10000,
                        MyFontEnum.Red);
                }
            }
        }

        void HandlePacket(PacketBase packet, ulong id, bool isFromServer)
        {
            var receivedPacketEventArgs = new ReceivedPacketEventArgs(
                packet.Id,
                packet.Data,
                id,
                isFromServer,
                NetworkDeserializer.Instance);

            if (packet.SendToAllPlayers && MyAPIGateway.Session.IsServer)
                TransmitPacketToAllPlayers(id, packet);

            if ((!isFromServer && MyAPIGateway.Session.IsServer) ||
                (isFromServer && (!MyAPIGateway.Session.IsServer || packet.SendToSender)))
            {
                var isKnown = false;
                DispatchGeneratedCallbacks(receivedPacketEventArgs, ref isKnown);
                if (!isKnown)
                {
                    MyLog.Default.WriteLineAndConsole(
                        $"[ADK.Network] Unexpected packet ID {packet.Id}");
                }
            }
        }

        partial void DispatchGeneratedCallbacks(ReceivedPacketEventArgs args, ref bool isKnown);

        void TransmitPacketToAllPlayers(ulong sender, PacketBase packet)
        {
            var tempPlayers = new List<IMyPlayer>(MyAPIGateway.Session.SessionSettings.MaxPlayers);
            MyAPIGateway.Players.GetPlayers(tempPlayers);

            foreach (var player in tempPlayers)
            {
                if (player.IsBot ||
                    player.SteamUserId == MyAPIGateway.Multiplayer.ServerId ||
                    (!packet.SendToSender && player.SteamUserId == sender))
                {
                    continue;
                }

                var raw = MyAPIGateway.Utilities.SerializeToBinary(packet);
                if (!SendToPlayer(raw, player.SteamUserId))
                {
                    MyLog.Default.WriteLineAndConsole(
                        $"[ADK.Network] Failed to forward packet {packet.Id} to player " +
                        $"{player.SteamUserId} ({raw.Length} bytes)");
                }
            }
        }

        bool SendToServer(byte[] raw)
        {
            if (raw == null)
                return false;

            if (raw.Length <= Parameters.MaxWirePacketBytes)
                return MyAPIGateway.Multiplayer.SendMessageToServer(_channelId, raw);

            return SendFragments(raw, null);
        }

        bool SendToPlayer(byte[] raw, ulong playerId)
        {
            if (raw == null)
                return false;

            if (raw.Length <= Parameters.MaxWirePacketBytes)
                return MyAPIGateway.Multiplayer.SendMessageTo(_channelId, raw, playerId);

            return SendFragments(raw, playerId);
        }

        bool SendFragments(byte[] raw, ulong? playerId)
        {
            var transferId = ++_nextFragmentTransferId;
            var totalChunks = (raw.Length + Parameters.MaxWirePacketBytes - 1) /
                              Parameters.MaxWirePacketBytes;
            MyLog.Default.WriteLineAndConsole(
                $"[ADK.Network] Sending fragmented packet {transferId} " +
                $"({raw.Length} bytes, {totalChunks} chunks)");

            for (var chunkIndex = 0; chunkIndex < totalChunks; chunkIndex++)
            {
                var offset = chunkIndex * Parameters.MaxWirePacketBytes;
                var size = Math.Min(Parameters.MaxWirePacketBytes, raw.Length - offset);
                var chunkData = new byte[size];
                Array.Copy(raw, offset, chunkData, 0, size);

                var fragment = new PacketFragment(
                    transferId,
                    chunkIndex,
                    totalChunks,
                    raw.Length,
                    chunkData);
                var packet = new PacketBase(NETWORK_FRAGMENT_ID, false, false);
                packet.Wrap(fragment);
                var fragmentRaw = MyAPIGateway.Utilities.SerializeToBinary(packet);

                var sent = playerId.HasValue
                    ? MyAPIGateway.Multiplayer.SendMessageTo(_channelId, fragmentRaw, playerId.Value)
                    : MyAPIGateway.Multiplayer.SendMessageToServer(_channelId, fragmentRaw);

                if (!sent)
                    return false;
            }

            return true;
        }

        bool TryAssembleFragment(
            PacketBase packet,
            ulong senderId,
            bool isFromServer,
            out byte[] raw)
        {
            raw = null;
            ExpireFragmentAssemblies();

            var fragment = MyAPIGateway.Utilities.SerializeFromBinary<PacketFragment>(packet.Data);
            if (fragment == null ||
                fragment.Data == null ||
                fragment.TotalChunks <= 0 ||
                fragment.TotalChunks > Parameters.MaxFragmentChunks ||
                fragment.ChunkIndex < 0 ||
                fragment.ChunkIndex >= fragment.TotalChunks ||
                fragment.TotalLength <= 0 ||
                fragment.TotalLength > Parameters.MaxFragmentedPacketBytes)
            {
                return false;
            }

            var key = senderId + ":" + isFromServer + ":" + fragment.TransferId;
            FragmentAssembly assembly;
            if (!_fragmentAssemblies.TryGetValue(key, out assembly))
            {
                assembly = new FragmentAssembly(fragment.TotalChunks, fragment.TotalLength);
                _fragmentAssemblies[key] = assembly;
            }
            else if (assembly.TotalChunks != fragment.TotalChunks ||
                     assembly.TotalLength != fragment.TotalLength)
            {
                _fragmentAssemblies.Remove(key);
                return false;
            }

            if (!assembly.Add(fragment))
                return false;

            raw = assembly.Assemble();
            _fragmentAssemblies.Remove(key);
            if (raw != null)
            {
                MyLog.Default.WriteLineAndConsole(
                    $"[ADK.Network] Reassembled fragmented packet {fragment.TransferId} " +
                    $"from {senderId} ({raw.Length} bytes)");
            }

            return raw != null;
        }

        void ExpireFragmentAssemblies()
        {
            if (_fragmentAssemblies.Count == 0)
                return;

            var now = DateTime.UtcNow.Ticks;
            var expired = new List<string>();
            foreach (var pair in _fragmentAssemblies)
            {
                if (now - pair.Value.CreatedUtcTicks > FragmentAssemblyExpiryTicks)
                    expired.Add(pair.Key);
            }

            for (var i = 0; i < expired.Count; i++)
                _fragmentAssemblies.Remove(expired[i]);
        }

        sealed class NetworkDeserializer : INetworkDeserializer
        {
            public static readonly NetworkDeserializer Instance = new NetworkDeserializer();

            public T Deserialize<T>(byte[] data)
            {
                return MyAPIGateway.Utilities.SerializeFromBinary<T>(data);
            }
        }

        [ProtoContract]
        sealed class PacketBase
        {
            [ProtoMember(1)] public readonly int Id;
            [ProtoMember(2)] public readonly bool SendToAllPlayers;
            [ProtoMember(3)] public readonly bool SendToSender;
            [ProtoMember(4)] public byte[] Data;

            public PacketBase()
            {
            }

            public PacketBase(int id, bool sendToAllPlayers, bool sendToSender)
            {
                Id = id;
                SendToAllPlayers = sendToAllPlayers;
                SendToSender = sendToSender;
            }

            public void Wrap(object data)
            {
                Data = MyAPIGateway.Utilities.SerializeToBinary(data);
            }
        }

        [ProtoContract]
        sealed class PacketFragment
        {
            [ProtoMember(1)] public int TransferId;
            [ProtoMember(2)] public int ChunkIndex;
            [ProtoMember(3)] public int TotalChunks;
            [ProtoMember(4)] public int TotalLength;
            [ProtoMember(5)] public byte[] Data;

            public PacketFragment()
            {
            }

            public PacketFragment(
                int transferId,
                int chunkIndex,
                int totalChunks,
                int totalLength,
                byte[] data)
            {
                TransferId = transferId;
                ChunkIndex = chunkIndex;
                TotalChunks = totalChunks;
                TotalLength = totalLength;
                Data = data;
            }
        }

        sealed class FragmentAssembly
        {
            readonly byte[][] _chunks;
            public readonly int TotalLength;
            public readonly int TotalChunks;
            public readonly long CreatedUtcTicks;
            int _receivedChunks;

            public FragmentAssembly(int totalChunks, int totalLength)
            {
                _chunks = new byte[totalChunks][];
                TotalChunks = totalChunks;
                TotalLength = totalLength;
                CreatedUtcTicks = DateTime.UtcNow.Ticks;
            }

            public bool Add(PacketFragment fragment)
            {
                if (fragment.ChunkIndex < 0 || fragment.ChunkIndex >= _chunks.Length)
                    return false;

                if (_chunks[fragment.ChunkIndex] != null)
                    return false;

                _chunks[fragment.ChunkIndex] = fragment.Data;
                _receivedChunks++;
                return _receivedChunks == _chunks.Length;
            }

            public byte[] Assemble()
            {
                var raw = new byte[TotalLength];
                var offset = 0;
                for (var i = 0; i < _chunks.Length; i++)
                {
                    var chunk = _chunks[i];
                    if (chunk == null || offset + chunk.Length > raw.Length)
                        return null;

                    Array.Copy(chunk, 0, raw, offset, chunk.Length);
                    offset += chunk.Length;
                }

                return offset == raw.Length ? raw : null;
            }
        }
    }
}
""";
}
