using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Adk.Analyzer;

[Generator]
public sealed class SingletonGenerator : IIncrementalGenerator
{
    const string SINGLETON_INTERFACE = "Generated.ISingleton<T>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ISingleton.g.cs", InterfaceSource));

        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntaxContext, _) =>
                    syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol != null)
            .Collect();

        context.RegisterSourceOutput(candidates, static (output, symbols) => EmitSingletons(output, symbols));
    }

    static void EmitSingletons(SourceProductionContext output, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var emitted = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var type in symbols)
        {
            if (!emitted.Add(type) || !IsSupportedSingleton(type))
                continue;

            output.AddSource(GetHintName(type), BuildSource(type));
        }
    }

    static bool IsSupportedSingleton(INamedTypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Class ||
            type.IsStatic ||
            type.Arity != 0 ||
            type.ContainingType != null ||
            !IsPartial(type))
        {
            return false;
        }

        return type.AllInterfaces.Any(interfaceType =>
            interfaceType.OriginalDefinition.ToDisplayString() == SINGLETON_INTERFACE &&
            interfaceType.TypeArguments.Length == 1 &&
            SymbolEqualityComparer.Default.Equals(interfaceType.TypeArguments[0], type));
    }

    static bool IsPartial(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is ClassDeclarationSyntax declaration &&
            declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    static string BuildSource(INamedTypeSymbol type)
    {
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ");
            builder.AppendLine(type.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
        }

        builder.Append("    ");
        AppendAccessibility(builder, type.DeclaredAccessibility);
        builder.Append("partial class ");
        builder.AppendLine(type.Name);
        builder.AppendLine("    {");
        builder.Append("        static ");
        builder.Append(typeName);
        builder.AppendLine(" _generatedSingletonInstance;");
        builder.AppendLine();
        builder.Append("        public static ");
        builder.Append(typeName);
        builder.AppendLine(" Instance { get { return _generatedSingletonInstance; } }");
        builder.AppendLine();
        builder.AppendLine("        public void RegisterSingleton()");
        builder.AppendLine("        {");
        builder.AppendLine("            if (_generatedSingletonInstance != null &&");
        builder.AppendLine("                !global::System.Object.ReferenceEquals(_generatedSingletonInstance, this))");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.InvalidOperationException(");
        builder.Append("                    \"A singleton instance is already registered for ");
        builder.Append(type.ToDisplayString());
        builder.AppendLine("\");");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            _generatedSingletonInstance = this;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public void UnregisterSingleton()");
        builder.AppendLine("        {");
        builder.AppendLine("            if (global::System.Object.ReferenceEquals(_generatedSingletonInstance, this))");
        builder.AppendLine("                _generatedSingletonInstance = null;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");

        if (!type.ContainingNamespace.IsGlobalNamespace)
            builder.AppendLine("}");
        return builder.ToString();
    }

    static void AppendAccessibility(StringBuilder builder, Accessibility accessibility)
    {
        if (accessibility == Accessibility.Public)
            builder.Append("public ");
        else if (accessibility == Accessibility.Internal)
            builder.Append("internal ");
    }

    static string GetHintName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", string.Empty)
                   .Replace(".", "_") + ".Singleton.g.cs";
    }

    const string InterfaceSource = @"// <auto-generated/>
namespace Generated
{
    public interface ISingleton<T> where T : class
    {
    }
}
";
}
